### ISSUE TITLE
Linux下乱码

### ISSUE THREAD

**Issue by ivaneye** [alim0x/atom-trans-en-zh#1]
windows下没有问题。
Linux下翻译乱码，
在trans-en-zh.less中添加
@font-family: 'WenQuanYi Micro Hei Mono','文泉驿微米黑','文泉驿等宽微米黑';
可解决乱码问题～

**Comment by zhiiwg** [comment]
我之前就是在 Linux 下编写的，插件中文乱码问题貌似和 Atom 本身有关系，我在 Atom 的样式表中指定了字体所以没有出现该问题。

```
.trans-en-zh {
    font-family: "Source Han Sans CN", "WenQuanYi Micro Hei", "PingFang SC", "Microsoft YaHei";
    font-size: 1.2em;
}
```

帮忙测试一下这样子还有问题没有 :)   @ivanpig

**Comment by ivaneye** [comment]
@alim0x OK了

**Comment by zhiiwg** [comment]
thx :+1:
